export const SHOW_ITEMS = 'SHOW_ITEMS';
export const LOADING_FLAG = 'LOADING_FLAG';
export const REQUEST_FRIDGE_ITEMS = 'REQUEST_FRIDGE_ITEMS';
export const RECEIVE_FRIDGE_ITEMS = 'RECEIVE_FRIDGE_ITEMS';