export const SHOW_ITEMS = 'SHOW_ITEMS';
export const LOADING_FLAG = 'LOADING_FLAG';
export const REQUEST_FRIDGE_ITEMS = 'REQUEST_FRIDGE_ITEMS';
export const RECEIVE_FRIDGE_ITEMS = 'RECEIVE_FRIDGE_ITEMS';
export const ADD_VEGETABLE_ITEM_REQUEST = 'ADD_VEGETABLE_ITEM_REQUEST';
export const DONE_ADD_VEGETABLE_ITEM_REQUEST = 'DONE_ADD_VEGETABLE_ITEM_REQUEST';
export const REQUEST_VEGE_ITEMS = 'REQUEST_VEGE_ITEMS';
export const RECEIVE_VEGE_ITEMS = 'RECEIVE_VEGE_ITEMS';